# Generated by Django 4.2.2 on 2023-06-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentanalysisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setiment',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
