# Generated by Django 4.2.2 on 2023-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentanalysisapp', '0002_setiment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setiment',
            name='text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
