# Generated by Django 4.2.2 on 2023-06-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentanalysisapp', '0003_alter_setiment_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setiment',
            new_name='Sentimenttb',
        ),
    ]
